# action.yml
name: 'Fix It'
description: 'Generate comby rules from a PR'
inputs:
  mountpoint:  # id of input
    description: 'Mount point for your repo'
    required: true
outputs:
  rules: # id of output
    description: 'rules fixit generated'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mountpoint }}