# action.yml
name: 'Fix It'
description: 'Generate comby rules from a PR'
inputs:
  pr:  # id of input
    description: 'PR to be merged in your repo'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
    volumes:
    - name: workspace
      path: /github/workspace
  args:
    - ${{ inputs.pr }}